language: android
jdk: oraclejdk7

sudo: false
env:
  global:
    #set the timeout to 8 for getting the tests done
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23
    - android-22

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - addon-google_apis-google-22
    # x86 is not functioning on travis for some reason
    #- sys-img-x86-addon-google_apis-google-23
    - sys-img-armeabi-v7a-addon-google_apis-google-22

script: ./gradlew assembleDebug connectedCheck

# Emulator Management: Create, Start and Wait
before_script:

  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:22" --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &