language: android

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    #set the timeout to avoid ShellCommandUnresponsiveException
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools

    - build-tools-23.0.3

    - android-22

    - extra-google-m2repository
    - extra-android-m2repository

    # !!! x86 and api 23 is not working on travis right now !!!
    - addon-google_apis-google-22
    - sys-img-armeabi-v7a-google_apis-22

  licenses:
      - 'android-sdk-license-.+'

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t "android-22" --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - sleep 30
  - adb devices
  - adb shell input keyevent 82 &

script:
  - echo $ADB_INSTALL_TIMEOUT
  - ./gradlew -PdisablePreDex testDebugUnitTest connectedDebugAndroidTest

after_script:
  - ./gradlew -PdisablePreDex testDebugUnitTestCoverage coveralls

after_failure:
  - android list targets