language: android

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - tools
    - platform-tools
    - build-tools

    - android-$ANDROID_API_LEVEL

    - extra-google-m2repository
    - extra-android-m2repository

    - addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL

  licenses:
      - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew
  - echo $ADB_INSTALL_TIMEOUT
  - android list targets

before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -data /home/travis/.android/avd/test.avd/userdata-qemu.im/userdata.img &
  - android-wait-for-emulator
  - sleep 30
  - adb devices
  - adb shell input keyevent 82 &

script:
  - ./gradlew -PdisablePreDex testDebugUnitTest connectedDebugAndroidTest

after_script:
  - ./gradlew -PdisablePreDex testDebugUnitTestCoverage coveralls
